[project]
name = "qc-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.16.4",
    "black>=25.1.0",
    "boto3>=1.39.6",
    "dotenv>=0.9.9",
    "elevenlabs>=2.7.1",
    "email-validator>=2.2.0",
    "fastapi>=0.116.1",
    "openai>=1.97.0",
    "passlib[bcrypt]>=1.7.4",
    "psycopg2>=2.9.10",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
    "python-dotenv>=1.1.1",
    "python-jose[cryptography]>=3.5.0",
    "python-multipart>=0.0.20",
    "sphinx>=8.2.3",
    "sphinx-autodoc-typehints>=3.2.0",
    "sphinx-rtd-theme>=3.0.2",
    "sqlalchemy>=2.0.41",
    "uvicorn[standard]>=0.35.0",
]
